export type NPC = {
  id: string;
  name: string;
  age: string;
  gender: string;
  role: string;
  location: string;
  personality: string;
  appearance: string;
  backstory: string;
  imageUrl: string;
  symbol: string;
  region: string;
};

export const npcs: NPC[] = [
  {
    id: "lily",
    name: "릴리",
    age: "22",
    gender: "여",
    role: "꽃집 운영",
    location: "피에르네 2층 거주",
    personality: "순수한 소녀 (ISFJ, 2w1)",
    appearance: "마름, 볼륨감, 땋아올린 금발, 적안, 다정한 미소",
    backstory: "순수하고 상냥한 이웃집 소녀, 마을 사람들에게 사랑받음.",
    imageUrl: "https://w7r.uk/1_%EB%A6%B4%EB%A6%AC.webp",
    symbol: "🌸",
    region: "마을 중앙"
  },
  {
    id: "dr_sue",
    name: "닥터 수",
    age: "32",
    gender: "여",
    role: "병원 의사",
    location: "2층 거주",
    personality: "엄격한 의사 (ESTJ, 1w2)",
    appearance: "큰 키, 늘씬, 볼륨, 흑발 뱅헤어, 자안, 검은 뿔테, 무표정",
    backstory: "깐깐한 성격. 연인 관계 시 진료실에서 은밀한 장난 치는 반전 매력.",
    imageUrl: "https://w7r.uk/1_%EB%8B%A5%ED%84%B0%EC%88%98.webp",
    symbol: "🩺",
    region: "마을 중앙"
  },
  {
    id: "madame_rose",
    name: "마담 로즈",
    age: "38",
    gender: "여",
    role: "주점 주인",
    location: "주점 안방 거주",
    personality: "매혹적인 성숙녀 (ENFJ, 2w3)",
    appearance: "풍만, 성숙, 짧은 흑발, 붉은빛 보라색 눈, 짙은 화장",
    backstory: "젊은 외모로 남성들을 홀리지만, 실제로는 사랑과 스킨십에 진중함.",
    imageUrl: "https://w7r.uk/1_%EB%A7%88%EB%8B%B4%20%EB%A1%9C%EC%A6%88.webp",
    symbol: "🍷",
    region: "마을 중앙"
  },
  {
    id: "catherine",
    name: "캐서린",
    age: "35",
    gender: "여",
    role: "주부",
    location: "잡화점 안집 거주",
    personality: "과묵한 주부 (ISTJ, 6w5)",
    appearance: "늘씬, 청록색 로우번, 차분한 무표정",
    backstory: "잡화점을 조용히 관리. 남편(피에르)과 금슬이 좋지 않지만 티 내지 않음.",
    imageUrl: "https://w7r.uk/1_%EC%BA%90%EC%84%9C%EB%A6%B0.webp",
    symbol: "🧹",
    region: "마을 중앙"
  },
  {
    id: "pierre",
    name: "피에르",
    age: "40",
    gender: "남",
    role: "잡화점 주인",
    location: "안집 거주",
    personality: "열정적인 상인 (ESFJ, 3w2)",
    appearance: "근육질, 자홍색 5대5 가르마, 갈안",
    backstory: "작물 직거래 파트너. 나이보다 젊어 보이려 애씀.",
    imageUrl: "https://w7r.uk/1_%ED%94%BC%EC%97%90%EB%A5%B4.webp",
    symbol: "🛒",
    region: "마을 중앙"
  },
  {
    id: "lewis",
    name: "루이스",
    age: "55",
    gender: "남",
    role: "촌장",
    location: "회관 근처 저택 거주",
    personality: "낭만적인 리더 (ENFJ, 4w3)",
    appearance: "다부짐, 넘긴 은발, 짧은 수염, 파이프 담배",
    backstory: "사별 후 아들(알렉스)과 거주. 농장 평가 및 축제 주최, 낭만적인 중년 가이드.",
    imageUrl: "https://w7r.uk/1_%EB%A3%A8%EC%9D%B4%EC%8A%A4.webp",
    symbol: "🎩",
    region: "마을 중앙"
  },
  {
    id: "alex",
    name: "알렉스",
    age: "24",
    gender: "남",
    role: "헬스 트레이너",
    location: "아버지(루이스)와 거주",
    personality: "과묵한 군인 타입 (ISTJ, 1w9)",
    appearance: "거대한 근육질, 흑발 페이드 컷, 갈안, 타이트한 민소매",
    backstory: "매일 체력 단련하는 스포츠맨. 아버지와 달리 진중하고 조용한 군인 타입.",
    imageUrl: "https://w7r.uk/1_%EC%95%8C%EB%A0%89%EC%8A%A4.webp",
    symbol: "🏋️",
    region: "마을 중앙"
  },
  {
    id: "mina",
    name: "미나",
    age: "27",
    gender: "여",
    role: "교사",
    location: "마을 중앙 거주",
    personality: "다정한 교사 (INFJ, 2w1)",
    appearance: "글래머, 좋은 비율, 애쉬블론드 반묶음, 청록안",
    backstory: "다정한 교사. 퇴근 후 동생(록시)의 당직 간식을 챙겨주는 착한 언니.",
    imageUrl: "https://w7r.uk/1_%EB%AF%B8%EB%82%98.webp",
    symbol: "📚",
    region: "마을 중앙"
  },
  {
    id: "becky",
    name: "베키",
    age: "21",
    gender: "여",
    role: "마트 알바생",
    location: "주점 장기 투숙",
    personality: "갸루 (ESFP, 7w8)",
    appearance: "육감적, 탄탄, 밝은 금발 단발, 풍선껌, 크롭 유니폼",
    backstory: "퉁명스러운 MZ 갸루. 모리스와 원조 교제하며 유흥비 지원받음.",
    imageUrl: "https://w7r.uk/1_%EB%B2%A0%ED%82%A4.webp",
    symbol: "💄",
    region: "마을 중앙"
  },
  {
    id: "roxy",
    name: "록시",
    age: "24",
    gender: "여",
    role: "경찰관",
    location: "파출소 당직실 거주",
    personality: "엄격한 경찰 (ESTJ, 8w9)",
    appearance: "넓은 골반, 탄탄, 금발 단발, 연보라안",
    backstory: "정직한 치안 유지자, 밤늦게 다니면 잔소리. 언니(미나)에게 항상 고마워함.",
    imageUrl: "https://w7r.uk/1_%EB%A1%9D%EC%8B%9C.webp",
    symbol: "🚓",
    region: "마을 중앙"
  },
  {
    id: "penny",
    name: "페니",
    age: "25",
    gender: "여",
    role: "가정교사",
    location: "루이스 집 2층 세입자",
    personality: "쿨데레 가정교사 (INTJ, 1w9)",
    appearance: "볼륨감, 늘씬, 보라색 긴 생머리, 청록안, 도도한 표정",
    backstory: "얼음여왕 같은 쿨데레. 계기가 생기면 정착할 생각 있음.",
    imageUrl: "https://w7r.uk/1_%ED%8E%98%EB%8B%88.webp",
    symbol: "📖",
    region: "마을 중앙"
  },
  {
    id: "elliott",
    name: "앨리엇",
    age: "28",
    gender: "남",
    role: "소설가",
    location: "해변 입구 오두막 거주",
    personality: "우울한 작가 (INFP, 4w5)",
    appearance: "우아, 마른 체형, 갈색 반묶음, 갈안",
    backstory: "고독과 사색을 즐기는 로맨티스트. 영감을 찾지만 먼저 말 걸지 않음.",
    imageUrl: "https://w7r.uk/1_%EC%95%A8%EB%A6%AC%EC%97%87.webp",
    symbol: "🖋️",
    region: "해변"
  },
  {
    id: "siren",
    name: "세이렌",
    age: "22",
    gender: "여",
    role: "낚시꾼",
    location: "부두 낚시 가게 거주",
    personality: "톰보이 라이벌 (ESTP, 7w6)",
    appearance: "탄탄, 구릿빛 피부, 흑발 숏컷, 보라안, 쾌활한 미소",
    backstory: "밝고 명랑한 톰보이. 플레이어와 낚시 대결을 하는 유쾌한 라이벌.",
    imageUrl: "https://w7r.uk/1_%EC%84%B8%EC%9D%B4%EB%A0%8C.webp",
    symbol: "🎣",
    region: "해변"
  },
  {
    id: "jack",
    name: "잭",
    age: "45",
    gender: "남",
    role: "생선 가게 주인",
    location: "해변 판잣집 거주",
    personality: "온화한 어부 (ISFP, 9w8)",
    appearance: "우람한 근육, 헝클어진 금발, 갈안, 턱수염",
    backstory: "과거 뱃사람, 지금은 마을에 정착. 낚시한 생선을 좋은 값에 매입.",
    imageUrl: "https://w7r.uk/1_%EC%9E%AD.webp",
    symbol: "🐟",
    region: "해변"
  },
  {
    id: "ariel",
    name: "아리엘",
    age: "26",
    gender: "여",
    role: "해양학자",
    location: "해변 연구소 거주",
    personality: "집착하는 과학자 (INTP, 5w6)",
    appearance: "여리여리, 분홍색 단발, 둥근 안경, 나른함",
    backstory: "바다 생물 연구에 깊이 몰입, 수집 퀘스트 제공.",
    imageUrl: "https://w7r.uk/1_%EC%95%84%EB%A6%AC%EC%97%98.webp",
    symbol: "🔬",
    region: "해변"
  },
  {
    id: "kai",
    name: "서퍼 카이",
    age: "25",
    gender: "남",
    role: "서퍼",
    location: "주점 장기 투숙",
    personality: "플레이보이 서퍼 (ESFP, 7w8)",
    appearance: "슬림, 근육질(식스팩), 젖은 금발, 푸른 눈, 상의 탈의",
    backstory: "맑은 날 해변에서 만남. 개방적이고 열정적인 플레이보이.",
    imageUrl: "https://w7r.uk/1_%EC%B9%B4%EC%9D%B4.webp",
    symbol: "🏄",
    region: "해변"
  },
  {
    id: "mori",
    name: "모리",
    age: "20대",
    gender: "여",
    role: "마녀",
    location: "숲 중턱 오두막 거주",
    personality: "게으른 마녀 (INTP, 5w4)",
    appearance: "늘씬, 볼륨감, 보라색 비대칭 단발, 주황안",
    backstory: "매사를 귀찮아함. 호감도 상승 시 사랑의 묘약 제조.",
    imageUrl: "https://w7r.uk/1_%EB%AA%A8%EB%A6%AC.webp",
    symbol: "🪄",
    region: "숲&산"
  },
  {
    id: "robin",
    name: "로빈",
    age: "33",
    gender: "여",
    role: "목수",
    location: "목공소 거주",
    personality: "호탕한 대장부 (ESTP, 8w7)",
    appearance: "활동적, 청발 단발, 하늘안, 명랑한 미소",
    backstory: "명랑, 호탕한 대장부 스타일. 자재를 주면 건물 건설.",
    imageUrl: "https://w7r.uk/1_%EB%A1%9C%EB%B9%88.webp",
    symbol: "🔨",
    region: "숲&산"
  },
  {
    id: "demetrius",
    name: "드미트리",
    age: "30",
    gender: "남",
    role: "과학자",
    location: "목공소 지하 연구실 거주",
    personality: "몰두하는 과학자 (INTJ, 5w6)",
    appearance: "마름, 은발, 둥근 안경, 무심한 표정",
    backstory: "로빈의 남편. 지하 연구에 몰두, 가끔 밤 산책. 생태계 퀘스트 제공.",
    imageUrl: "https://w7r.uk/1_%EB%93%9C%EB%AF%B8%ED%8A%B8%EB%A6%AC.webp",
    symbol: "🧪",
    region: "숲&산"
  },
  {
    id: "sebastian",
    name: "세바스찬",
    age: "25",
    gender: "남",
    role: "프로그래머",
    location: "목공소 2층 세입자",
    personality: "히키코모리 (INTP, 5w6)",
    appearance: "마름, 슬림, 녹흑발, 헤드폰",
    backstory: "히키코모리 공대생, 눈치 없고 직설적. 매일 주점에서 식사.",
    imageUrl: "https://w7r.uk/1_%EC%84%B8%EB%B0%94%EC%8A%A4%EC%B0%AC.webp",
    symbol: "💻",
    region: "숲&산"
  },
  {
    id: "luna",
    name: "루나",
    age: "24",
    gender: "여",
    role: "점술가",
    location: "숲 속 집시 텐트 거주",
    personality: "신비로운 예언자 (INFJ, 5w4)",
    appearance: "여리여리, 붉은 단발, 녹안, 무표정",
    backstory: "날씨와 행운 점괘. 늘 플레이어가 올 것을 알고 있음.",
    imageUrl: "https://w7r.uk/1_%EB%A3%A8%EB%82%98.webp",
    symbol: "🔮",
    region: "숲&산"
  },
  {
    id: "linus",
    name: "라이너",
    age: "45",
    gender: "남",
    role: "산지기",
    location: "산 입구 나무집 거주",
    personality: "과묵한 생존자 (ISTP, 9w8)",
    appearance: "최장신, 탄탄한 근육, 선글라스",
    backstory: "과묵, 진중한 자연인. 생존 기술 전수, 남는 장비 제공.",
    imageUrl: "https://w7r.uk/1_%EB%9D%BC%EC%9D%B4%EB%84%88.webp",
    symbol: "⛺",
    region: "숲&산"
  },
  {
    id: "nymph",
    name: "님프",
    age: "미상",
    gender: "여",
    role: "요정",
    location: "비밀의 숲",
    personality: "메스가키 (ENTP, 7w8)",
    appearance: "단신, 글래머, 뾰족귀, 은발, 분홍안",
    backstory: "히든 NPC. 얄미운 메스가키, 마법으로 체력/기력 회복.",
    imageUrl: "https://w7r.uk/1_%EB%8B%98%ED%94%84.webp",
    symbol: "🧚",
    region: "숲&산"
  },
  {
    id: "yuyu",
    name: "유유",
    age: "20",
    gender: "남",
    role: "온천 관리인",
    location: "산 중턱 온천 거주",
    personality: "도짓코 관리인 (ISFP, 6w7)",
    appearance: "왜소, 마름, 젖은 탱크톱, 맑은 갈안",
    backstory: "순수, 소심한 소년. 덜렁대는 도짓코, 부끄러워하며 시키는 건 다 함.",
    imageUrl: "https://w7r.uk/1_%EC%9C%A0%EC%9C%A0.webp",
    symbol: "♨️",
    region: "숲&산"
  },
  {
    id: "marnie",
    name: "마니",
    age: "30",
    gender: "여",
    role: "목장 주인",
    location: "목장 본채 거주",
    personality: "쾌활한 목장주 (ESFJ, 2w3)",
    appearance: "튼튼함, 넓은 골반, 주황색 숏컷, 적안, 활짝 웃는 표정",
    backstory: "친절, 명랑, 에너지 넘치는 목장 누님. 가축과 건초 판매.",
    imageUrl: "https://w7r.uk/1_%EB%A7%88%EB%8B%88.webp",
    symbol: "🐄",
    region: "농경지"
  },
  {
    id: "shane",
    name: "셰인",
    age: "29",
    gender: "남",
    role: "물류직",
    location: "목장 창고 세입자",
    personality: "자멸적인 외톨이 (ISTP, 4w5)",
    appearance: "건장, 흑청색 투블럭, 수염 자국, 담배",
    backstory: "우울증, 술/담배 중독. 호감도 상승 시 마음을 열고 갱생 가능.",
    imageUrl: "https://w7r.uk/1_%EC%85%B0%EC%9D%B8.webp",
    symbol: "🍺",
    region: "농경지"
  },
  {
    id: "claire",
    name: "클레어",
    age: "30",
    gender: "여",
    role: "지점장",
    location: "서쪽 주택 거주",
    personality: "야심찬 임원 (ENTJ, 3w4)",
    appearance: "슬림, 단정, 흑발, 뿔테, 노란안, 여유로운 미소",
    backstory: "능력을 중시하는 커리어우먼. 남편(모리스)과 야망 코드가 맞음.",
    imageUrl: "https://w7r.uk/1_%ED%81%B4%EB%A0%88%EC%96%B4.webp",
    symbol: "💼",
    region: "스카페 마트"
  },
  {
    id: "morris",
    name: "모리스",
    age: "32",
    gender: "남",
    role: "매니저",
    location: "서쪽 주택 거주",
    personality: "무자비한 출세주의자 (ENTJ, 3w2)",
    appearance: "좋은 비율, 흑발 포마드, 날카로운 녹안, 얇은 안경",
    backstory: "성공 지향적, 무능력 혐오. 베키를 능력 없는 장난감 취급.",
    imageUrl: "https://w7r.uk/1_%EB%AA%A8%EB%A6%AC%EC%8A%A4.webp",
    symbol: "📈",
    region: "스카페 마트"
  },
  {
    id: "slime_girl",
    name: "슬라임 걸",
    age: "100+",
    gender: "여",
    role: "몬스터",
    location: "지하 깊은 동굴",
    personality: "순진한 몬스터 (ENFP, 7w6)",
    appearance: "글래머, 투명한 슬라임 바디, 하늘색 단발, 녹안, 전라",
    backstory: "인간 형태의 순수한 몬스터. 인간에게 무해, 장난기 많음.",
    imageUrl: "https://w7r.uk/1_%EC%8A%AC%EB%9D%BC%EC%9E%84%EA%B1%B8.webp",
    symbol: "💧",
    region: "광산 & 기타"
  },
  {
    id: "raccoon",
    name: "라쿤",
    age: "미상",
    gender: "남",
    role: "유통업자",
    location: "바다 위 함선 거주",
    personality: "트릭스터 상인 (ENTP, 7w6)",
    appearance: "인간 비율 라쿤 수인, 페도라, 정장",
    backstory: "매달 정해진 날에 함선으로 방문. 희귀, 특수 물품 판매.",
    imageUrl: "https://w7r.uk/1_%EB%AF%B8%EC%8A%A4%ED%84%B0%EB%9D%BC%EC%BF%A4.webp",
    symbol: "🦝",
    region: "광산 & 기타"
  }
];
