export type Region = '거주 구역' | '자연 구역' | '직업활동 구역' | '기타';

export type NPC = {
  id: string;
  name: string;
  age: string;
  gender: string;
  role: string;
  personality: string;
  appearance: string;
  backstory: string;
  imageUrl: string;
  symbol: string;
  region: Region;
};

export const npcs: NPC[] = [
  {
    id: "lily",
    name: "릴리",
    age: "22",
    gender: "여",
    role: "꽃집 운영",
    personality: "ISFJ+2w1",
    appearance: "마름, 볼륨감, 땋아올린 금발, 적안",
    backstory: "순수하고 상냥한 이웃집 소녀, 마을 사람들에게 사랑받음.",
    imageUrl: "https://w7r.uk/1_%EB%A6%B4%EB%A6%AC.webp",
    symbol: "🌸",
    region: "거주 구역"
  },
  {
    id: "dr_sue",
    name: "닥터 수",
    age: "32",
    gender: "여",
    role: "의사",
    personality: "ESTJ+1w2",
    appearance: "큰 키, 늘씬, 볼륨, 흑발 뱅헤어, 자안, 검은 뿔테",
    backstory: "깐깐한 성격. 연인 관계 시 진료실에서 은밀한 장난 치는 반전 매력. 약국 위층에 병원 있음.",
    imageUrl: "https://w7r.uk/1_%EB%8B%A5%ED%84%B0%EC%88%98.webp",
    symbol: "🩺",
    region: "거주 구역"
  },
  {
    id: "madame_rose",
    name: "마담 로즈",
    age: "38",
    gender: "여",
    role: "주점 주인",
    personality: "ENFJ+2w3",
    appearance: "풍만, 성숙, 짧은 흑발, 붉은빛 보라색 눈, 짙은 화장",
    backstory: "젊은 외모로 남성들을 홀리지만, 실제로는 사랑과 스킨십에 진중함.",
    imageUrl: "https://w7r.uk/1_%EB%A7%88%EB%8B%B4%20%EB%A1%9C%EC%A6%88.webp",
    symbol: "🍷",
    region: "거주 구역"
  },
  {
    id: "roxy",
    name: "록시",
    age: "24",
    gender: "여",
    role: "파출소대원",
    personality: "ESTJ+8w9",
    appearance: "넓은 골반, 탄탄, 금발 단발, 연보라안",
    backstory: "정직한 치안 유지자, 밤늦게 다니면 잔소리. 언니(나탈리)에게 항상 고마워함.",
    imageUrl: "https://w7r.uk/1_%EB%A1%9D%EC%8B%9C.webp",
    symbol: "🚓",
    region: "거주 구역"
  },
  {
    id: "siren",
    name: "세이렌",
    age: "22",
    gender: "여",
    role: "낚시꾼",
    personality: "ESTP+7w6",
    appearance: "탄탄, 구릿빛 피부, 흑발 숏컷, 보라안",
    backstory: "밝고 명랑한 톰보이. 플레이어와 낚시 대결을 하는 유쾌한 라이벌.",
    imageUrl: "https://w7r.uk/1_%EC%84%B8%EC%9D%B4%EB%A0%8C.webp",
    symbol: "🎣",
    region: "자연 구역"
  },
  {
    id: "ariel",
    name: "아리엘",
    age: "26",
    gender: "여",
    role: "생태학자",
    personality: "INTP",
    appearance: "여리여리, 분홍색 단발, 둥근 안경, 나른함",
    backstory: "바다 생물 연구에 깊이 몰입, 수집 퀘스트 제공.",
    imageUrl: "https://w7r.uk/1_%EC%95%84%EB%A6%AC%EC%97%98.webp",
    symbol: "🔬",
    region: "자연 구역"
  },
  {
    id: "kai",
    name: "카이",
    age: "25",
    gender: "남",
    role: "프로 서퍼",
    personality: "ESFP+7w8",
    appearance: "슬림, 근육질, 젖은 금발, 푸른 눈, 상의 탈의",
    backstory: "맑은 날 해변에서 만남. 개방적이고 열정적인 플레이보이.",
    imageUrl: "https://w7r.uk/1_%EC%B9%B4%EC%9D%B4.webp",
    symbol: "🏄",
    region: "자연 구역"
  },
  {
    id: "nymph",
    name: "님프",
    age: "미상",
    gender: "여",
    role: "요정",
    personality: "ENTP+7w8",
    appearance: "단신, 글래머, 뾰족귀, 은발, 분홍안",
    backstory: "히든 NPC. 얄미운 메스가키, 마법으로 체력/기력 회복.",
    imageUrl: "https://w7r.uk/1_%EB%8B%98%ED%94%84.webp",
    symbol: "🧚",
    region: "기타"
  },
  {
    id: "yuyu",
    name: "유유",
    age: "20",
    gender: "남",
    role: "관리인",
    personality: "ISFP+6w7",
    appearance: "왜소, 마름, 젖은 탱크톱, 맑은 갈안",
    backstory: "순수, 소심한 소년. 덜렁대는 도짓코, 부끄러워하며 시키는 건 다 함.",
    imageUrl: "https://w7r.uk/1_%EC%9C%A0%EC%9C%A0.webp",
    symbol: "♨️",
    region: "기타"
  },
  {
    id: "slime_girl",
    name: "슬라임걸",
    age: "100+",
    gender: "여",
    role: "몬스터",
    personality: "ENFP+7w6",
    appearance: "글래머, 투명한 슬라임 바디, 하늘색 단발, 녹안, 전라",
    backstory: "인간 형태의 순수한 몬스터. 인간에게 무해, 장난기 많음.",
    imageUrl: "https://w7r.uk/1_%EC%8A%AC%EB%9D%BC%EC%9E%84%EA%B1%B8.webp",
    symbol: "💧",
    region: "기타"
  },
  {
    id: "margaret",
    name: "마가렛",
    age: "30",
    gender: "여",
    role: "구멍가게 주인",
    personality: "ISTJ+6w5",
    appearance: "마름, 청록색 로우번",
    backstory: "돌아가신 할머니에게 물려받은 구멍가게를 운영중. user의 물건을 매입해서 대도시에 유통해주기도 한다.",
    imageUrl: "https://w7r.uk/1_%EC%BA%90%EC%84%9C%EB%A6%B0.webp",
    symbol: "🏪",
    region: "직업활동 구역"
  },
  {
    id: "brooks",
    name: "브룩스",
    age: "30",
    gender: "남",
    role: "귀농 방송인",
    personality: "ESFJ+3w2",
    appearance: "근육질, 자홍색 5대5 가르마, 갈안",
    backstory: "귀농을 해보겠다며 당차게 도시생활을 접고 마을로 온 개인 인터넷 방송인. 구독자나 실시간 시청자는 10명 언저리이다.",
    imageUrl: "https://w7r.uk/1_%ED%94%BC%EC%97%90%EB%A5%B4.webp",
    symbol: "📱",
    region: "직업활동 구역"
  },
  {
    id: "watson",
    name: "왓슨",
    age: "60",
    gender: "남",
    role: "마을 대표",
    personality: "ENFJ+4w3",
    appearance: "다부짐, 넘긴 은발, 짧은 수염, 파이프 담배",
    backstory: "사별 후 아들(제레미)과 거주. 마을 행사 주최자.",
    imageUrl: "https://w7r.uk/1_%EB%A3%A8%EC%9D%B4%EC%8A%A4.webp",
    symbol: "🎩",
    region: "거주 구역"
  },
  {
    id: "jeremy",
    name: "제레미",
    age: "30",
    gender: "남",
    role: "방범대",
    personality: "ISTJ+1w9",
    appearance: "거대한 근육질, 흑발 페이드 컷, 갈안, 타이트한 민소매",
    backstory: "군인 퇴직 후 마을에서 아버지의 권유로 방범대 활동 중.",
    imageUrl: "https://w7r.uk/1_%EC%95%8C%EB%A0%89%EC%8A%A4.webp",
    symbol: "🛡️",
    region: "거주 구역"
  },
  {
    id: "natalie",
    name: "나탈리",
    age: "27",
    gender: "여",
    role: "교사",
    personality: "INFJ+2w1",
    appearance: "글래머, 좋은 비율, 애쉬블론드 반묶음, 청록안",
    backstory: "다정한 교사. 퇴근 후 동생(록시)의 당직 간식을 챙겨주는 착한 언니.",
    imageUrl: "https://w7r.uk/1_%EB%AF%B8%EB%82%98.webp",
    symbol: "📚",
    region: "거주 구역"
  },
  {
    id: "becky",
    name: "베키",
    age: "21",
    gender: "여",
    role: "농약 가게 직원",
    personality: "ESFP+7w8",
    appearance: "육감적, 탄탄, 밝은 금발 단발, 풍선껌, 크롭 유니폼",
    backstory: "퉁명스러운 MZ 갸루. 가게 사장님과 자주 싸운다. 상경하고 싶지만 부모님때문에 못하는중. 돈을 모으는 중.",
    imageUrl: "https://w7r.uk/1_%EB%B2%A0%ED%82%A4.webp",
    symbol: "💄",
    region: "직업활동 구역"
  },
  {
    id: "timothy",
    name: "티모시",
    age: "28",
    gender: "남",
    role: "사진작가",
    personality: "INFP+4w5",
    appearance: "우아, 마른 체형, 갈색 반묶음, 갈안",
    backstory: "로맨티스트. 마을의 이쁜 곳을 찾아 다니는 사람. 이쁜 사진들을 찍어 사진전을 열기 위해 직접 마을을 찾아온 청년.",
    imageUrl: "https://w7r.uk/1_%EC%95%A8%EB%A6%AC%EC%97%87.webp",
    symbol: "📸",
    region: "자연 구역"
  },
  {
    id: "dylan",
    name: "딜런",
    age: "35",
    gender: "남",
    role: "배관공",
    personality: "ISFP+9w8",
    appearance: "우람한 근육, 헝클어진 금발, 갈안, 턱수염",
    backstory: "마을의 배관을 담당하는 배관공. 손재주가 좋아 여러 기계들을 고치는 일도 한다.",
    imageUrl: "https://w7r.uk/1_%EC%9E%AD.webp",
    symbol: "🔧",
    region: "직업활동 구역"
  },
  {
    id: "sharon",
    name: "샤론",
    age: "25",
    gender: "여",
    role: "백수",
    personality: "INTJ+1w9",
    appearance: "볼륨감, 늘씬, 보라색 긴 생머리, 청록안",
    backstory: "얼음여왕 같은 쿨데레. 유학파. 도시 생활에 지쳐 내려와 살음. 계기가 생기면 정착할 생각 있음.",
    imageUrl: "https://w7r.uk/1_%ED%8E%98%EB%8B%88.webp",
    symbol: "❄️",
    region: "거주 구역"
  },
  {
    id: "mori",
    name: "모리",
    age: "20",
    gender: "여",
    role: "자칭 연금술사",
    personality: "INTP+5w4",
    appearance: "늘씬, 볼륨감, 보라색 비대칭 단발, 주황안",
    backstory: "연금술을 믿는 소녀. 포션이란 것을 만들 수 있다고 주장함.",
    imageUrl: "https://w7r.uk/1_%EB%AA%A8%EB%A6%AC.webp",
    symbol: "🪄",
    region: "자연 구역"
  },
  {
    id: "thompson",
    name: "톰슨",
    age: "30",
    gender: "남",
    role: "약사",
    personality: "INTJ+5w6",
    appearance: "마름, 은발, 둥근 안경, 무심한 표정",
    backstory: "약사. 가끔 밤 산책. 닥터 수 병원 건물 1층에서 약국을 운영.",
    imageUrl: "https://w7r.uk/1_%EB%93%9C%EB%AF%B8%ED%8A%B8%EB%A6%AC.webp",
    symbol: "💊",
    region: "직업활동 구역"
  },
  {
    id: "jacob",
    name: "제이콥",
    age: "25",
    gender: "남",
    role: "무직",
    personality: "INTP+5w6",
    appearance: "마름, 슬림, 녹흑발, 헤드폰",
    backstory: "히키코모리, 눈치 없고 직설적. 식사는 주점에서 해결. 코인과 주식 트레이딩을 업으로 삼고 있다. 도시로 상경을 원한다.",
    imageUrl: "https://w7r.uk/1_%EC%84%B8%EB%B0%94%EC%8A%A4%EC%B0%AC.webp",
    symbol: "💻",
    region: "거주 구역"
  },
  {
    id: "logan",
    name: "로건",
    age: "40",
    gender: "남",
    role: "벌목업자",
    personality: "ISTP+9w8",
    appearance: "최장신, 탄탄한 근육, 선글라스",
    backstory: "과묵, 진중한 자연인. 생존 기술 전수, 안 쓰는 도끼 제공.",
    imageUrl: "https://w7r.uk/1_%EB%9D%BC%EC%9D%B4%EB%84%88.webp",
    symbol: "🪓",
    region: "자연 구역"
  },
  {
    id: "scott",
    name: "스콧",
    age: "28",
    gender: "남",
    role: "소방대원",
    personality: "ISTP+4w5",
    appearance: "건장, 흑청색 투블럭, 수염 자국, 담배",
    backstory: "담배를 피지만 불조심하라고 잔소리한다. 당직인원이 부족해 퇴근 후 늘 피곤해보인다.",
    imageUrl: "https://w7r.uk/1_%EC%85%B0%EC%9D%B8.webp",
    symbol: "🚒",
    region: "직업활동 구역"
  },
  {
    id: "betty",
    name: "베티",
    age: "24",
    gender: "여",
    role: "종축업자",
    personality: "ESFJ+2w3",
    appearance: "튼튼함, 넓은 골반, 주황색 숏컷, 적안",
    backstory: "가족과 함께 가축 새끼를 전문으로 기르는 목장 운영. 필요한 가축을 살 수 있다.",
    imageUrl: "https://w7r.uk/1_%EB%A7%88%EB%8B%88.webp",
    symbol: "🐄",
    region: "직업활동 구역"
  },
  {
    id: "amber",
    name: "앰버",
    age: "30",
    gender: "여",
    role: "전기 설비업자",
    personality: "ESTP+8w7",
    appearance: "활동적, 청발 단발, 하늘안",
    backstory: "두꺼비집이 내려가면 먼저 달려와 고쳐주는 사람. 기계 쪽 보다는 가정집이나 안전 설비등을 전문으로 봐준다.",
    imageUrl: "https://w7r.uk/1_%EB%A1%9C%EB%B9%88.webp",
    symbol: "⚡",
    region: "직업활동 구역"
  },
  {
    id: "amanda",
    name: "아만다",
    age: "24",
    gender: "여",
    role: "조향사",
    personality: "INFJ+5w4",
    appearance: "여리여리, 붉은 단발, 녹안, 무표정",
    backstory: "도시에서는 향기가 묻혀 버려 한적한 시골 마을로 이주 온 조향사. 그녀의 공방에서는 늘 향기로운 향이 나온다.",
    imageUrl: "https://w7r.uk/1_%EB%A3%A8%EB%82%98.webp",
    symbol: "🧪",
    region: "직업활동 구역"
  },
  {
    id: "victoria",
    name: "빅토리아",
    age: "30",
    gender: "여",
    role: "은행직원",
    personality: "ENTJ+3w4",
    appearance: "슬림, 단정, 흑발, 뿔테, 노란안",
    backstory: "커리어우먼. 은행에 직원이 많이 없어 주로 혼자 잔업까지 하는 인물. 도시로 발령받고 싶어함.",
    imageUrl: "https://w7r.uk/1_%ED%81%B4%EB%A0%88%EC%96%B4.webp",
    symbol: "💼",
    region: "직업활동 구역"
  },
  {
    id: "liam",
    name: "리암",
    age: "32",
    gender: "남",
    role: "우체국직원",
    personality: "ENTJ+3w2",
    appearance: "좋은 비율, 흑발 포마드, 날카로운 녹안, 얇은 안경",
    backstory: "늘 우체부들을 하대하는 인물. 그러나 실상은 우체부들이 근무태만이라 자주 혼내는 것임.",
    imageUrl: "https://w7r.uk/1_%EB%AA%A8%EB%A6%AC%EC%8A%A4.webp",
    symbol: "✉️",
    region: "직업활동 구역"
  }
];
